---
  - hosts: localhost
    vars_files:
      - ./vars/vars_conf.yml


    tasks:

      - name: Ansible replace entity
        replace:
          path: ./files/template_nifi.xml
          regexp: "{entity}"
          replace: "{{ entity }}"

      - name: Ansible replace trigram
        replace:
          path: ./files/template_nifi.xml
          regexp: "{trigram}"
          replace: "{{ trigram }}"

      - name: Ansible replace _{sub_project}_
        replace:
          path: ./files/template_nifi.xml
          regexp: "_{sub_project}_"
          replace: "_"
        
      - name: Ansible replace sub_project
        replace:
          path: ./files/template_nifi.xml
          regexp: "{sub_project}"
        when:  sub_project == ""

      - name: Ansible replace sub_project
        replace:
          path: ./files/template_nifi.xml
          regexp: "{sub_project}"
        when:  sub_project != ""

      - name: Ansible replace Kerberos name
        replace:
          path: ./files/template_nifi.xml
          regexp: "{kerberos_principal}"
          replace: "{{ kerberos_principal }}"  

      - name: Ansible replace Kerberos Keytab
        replace:
          path: ./files/template_nifi.xml
          regexp: "{kerberos_keytab}"
          replace: "{{ kerberos_keytab }}"

      - name: Ansible replace Path Hdfs
        replace:
          path: ./files/template_nifi.xml
          regexp: "{path_hdfs}"
          replace: "{{ path_hdfs }}"


      - name: Ansible replace Topic Name
        replace:
          path: ./files/template_nifi.xml
          regexp: "{topic}"
          replace: "{{ topic}}"


      - name: Ansible replace Es Url
        replace:
          path: ./files/template_nifi.xml
          regexp: "{es_url}"
          replace: "{{ es_url }}"
      - name: Ansible replace Es Index
        replace:
          path: ./files/template_nifi.xml
          regexp: "{es_index}"
          replace: "{{ es_index }}"

      - name: Ansible replace Es User
        replace:
          path: ./files/template_nifi.xml
          regexp: "{es_user}"
          replace: "{{ es_user }}"

      - name: Ansible replace Kafka Brokers
        replace:
          path: ./files/template_nifi.xml
          regexp: "{kafka_brokers}"
          replace: "{{ kafka_brokers }}"
